#!/bin/bash
# bash -c "clear && docker exec -it runestoneserver_runestone_1 bash -c 'cd applications/runestone/tests; python run_tests.py'"

echo "$@"
basecomm="cd applications/runestone/books/$1; runestone build --all deploy"
docker exec -it runestoneserver_runestone_1 bash -c "$basecomm"

