#!/bin/bash
# bash -c "clear && docker exec -it runestoneserver_runestone_1 bash -c 'cd applications/runestone/tests; python run_tests.py'"

echo "$@"
container=`docker ps -a | egrep 'runestone/server|runestoneserver_runestone' | awk '{print $1}'`
basecommand="psql \$DEV_DBURL"
echo $basecommand
docker exec -it $container bash -c "$basecommand"

