#!/bin/bash
# bash -c "clear && docker exec -it runestoneserver_runestone_1 bash -c 'cd applications/runestone/tests; python run_tests.py'"

echo "$@"
basecommand="rsmanage $@"
echo $basecommand
docker exec -it runestoneserver_runestone_1 bash -c "$basecommand"

