#!/bin/bash
# bash -c "clear && docker exec -it runestoneserver_runestone_1 bash -c 'cd applications/runestone/tests; python run_tests.py'"

container=`docker ps -a | grep runestone/server | awk '{print $1}'`
docker exec -it $container bash -c "bash"

