#!/bin/bash
# bash -c "clear && docker exec -it runestoneserver_runestone_1 bash -c 'cd applications/runestone/tests; python run_tests.py'"

echo "$@"
basecomm="cd applications/runestone/tests; cp .coveragerc ../../../; pytest"
dcomm="$basecomm $@"
docker exec -it runestoneserver_runestone_1 bash -c "$dcomm"

