#!/bin/bash
# bash -c "clear && docker exec -it runestoneserver_runestone_1 bash -c 'cd applications/runestone/tests; python run_tests.py'"

echo "$@"
basecomm="cp applications/runestone/tests/.coveragerc .; pytest applications/runestone/tests"
dcomm="$basecomm $@"
docker exec -it runestoneserver_runestone_1 bash -c "$dcomm"

