#!/bin/bash
# bash -c "clear && docker exec -it runestoneserver_runestone_1 bash -c 'cd applications/runestone/tests; python run_tests.py'"

if [ $# -eq 0 ]
  then
    echo "Usage:  dbuild basecourse "
    echo "    the basecourse should be in the database and should match the"
    echo "    top level folder name of the book you want to build as well as"
    echo "    the project_name in your pavement.py file."
    exit -1
fi

echo "$@"
container=`docker ps -a | grep runestone/server | awk '{print $1}'`
basecomm="cd applications/runestone/books/$1; runestone build deploy"
docker exec -it $container bash -c "$basecomm"

