#!/bin/bash

# A simple script to start web2py and the companion scheduler app for building
# books.  Copy these into the main web2py folder and use them there
#

export DBUSER=bmiller
export DBPASS=''
export DBHOST=localhost
export DBNAME=runestone

echo "Be sure to activate your virtual environment"
#source ~/Environments/web2py/bin/activate
python web2py.py --ip=0.0.0.0 --port=8000 --password='<recycle>' -K runestone --nogui -X  &
sleep 3
echo "starting scheduler"
python run_scheduler.py &


